# Generated by Django 5.0.6 on 2024-06-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('bahan', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Makanan',
            },
        ),
    ]
